/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javafx.scene.control.TabPane;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author April10
 */
public class ManagementOrder extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public ManagementOrder() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtJudulLaundry = new javax.swing.JLabel();
        txtAlamatLaundry = new javax.swing.JLabel();
        btnMenuUtama = new javax.swing.JButton();
        btnManajemenPelanggan = new javax.swing.JButton();
        btnManajemenOrder = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnMonitoring = new javax.swing.JButton();
        btnPengaturan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TabPanel = new javax.swing.JTabbedPane();
        PanelBelumDiCuci = new javax.swing.JPanel();
        txtFilterTBUser = new javax.swing.JTextField();
        btnSedangDiProses = new javax.swing.JButton();
        btnSudahDiAmbil = new javax.swing.JButton();
        btnBelumDiAmbil = new javax.swing.JButton();
        btnHapusOrder = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableBelumDiCuci = new javax.swing.JTable();
        PanelSedangDiProses = new javax.swing.JPanel();
        txtFilterTBUser1 = new javax.swing.JTextField();
        btnSudahDiAmbil1 = new javax.swing.JButton();
        btnBelumDiAmbil1 = new javax.swing.JButton();
        btnHapusOrder1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableSedangDiProses = new javax.swing.JTable();
        PanelBelumDiCuci2 = new javax.swing.JPanel();
        txtFilterTBUser2 = new javax.swing.JTextField();
        btnSudahDiAmbil2 = new javax.swing.JButton();
        btnHapusOrder2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableBelumDiAmbil = new javax.swing.JTable();
        PanelBelumDiCuci3 = new javax.swing.JPanel();
        txtFilterTBUser3 = new javax.swing.JTextField();
        btnHapusOrder3 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        TableSudahDiAmbil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(108, 122, 137));

        txtJudulLaundry.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        txtJudulLaundry.setForeground(new java.awt.Color(255, 255, 255));
        txtJudulLaundry.setText("Nama Laundry");

        txtAlamatLaundry.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAlamatLaundry.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamatLaundry.setText("Alamat");
        txtAlamatLaundry.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnMenuUtama.setBackground(new java.awt.Color(92, 151, 191));
        btnMenuUtama.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMenuUtama.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Home_32px.png"))); // NOI18N
        btnMenuUtama.setText("    Menu Utama");
        btnMenuUtama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenuUtama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUtamaActionPerformed(evt);
            }
        });

        btnManajemenPelanggan.setBackground(new java.awt.Color(92, 151, 191));
        btnManajemenPelanggan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnManajemenPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnManajemenPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/User Groups_32px_6.png"))); // NOI18N
        btnManajemenPelanggan.setText("    Pelanggan");
        btnManajemenPelanggan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManajemenPelanggan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnManajemenOrder.setBackground(new java.awt.Color(92, 151, 191));
        btnManajemenOrder.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnManajemenOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnManajemenOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Shopping Basket_32px.png"))); // NOI18N
        btnManajemenOrder.setText("    Pesanan");
        btnManajemenOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManajemenOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnLaporan.setBackground(new java.awt.Color(92, 151, 191));
        btnLaporan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Stocks_32px_3.png"))); // NOI18N
        btnLaporan.setText("    Laporan");
        btnLaporan.setToolTipText("");
        btnLaporan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnMonitoring.setBackground(new java.awt.Color(92, 151, 191));
        btnMonitoring.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMonitoring.setForeground(new java.awt.Color(255, 255, 255));
        btnMonitoring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/System Information_32px.png"))); // NOI18N
        btnMonitoring.setText("    Monitoring");
        btnMonitoring.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMonitoring.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnPengaturan.setBackground(new java.awt.Color(92, 151, 191));
        btnPengaturan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnPengaturan.setForeground(new java.awt.Color(255, 255, 255));
        btnPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Settings_32px.png"))); // NOI18N
        btnPengaturan.setText("    Pengaturan");
        btnPengaturan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPengaturan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMonitoring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManajemenOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManajemenPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAlamatLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtJudulLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtJudulLaundry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlamatLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManajemenPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManajemenOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMonitoring, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(108, 122, 137));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 76, 60)));
        jPanel5.setForeground(new java.awt.Color(231, 76, 60));

        jPanel6.setBackground(new java.awt.Color(92, 151, 191));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Form_32px.png"))); // NOI18N
        jLabel4.setText("Manajemen Order");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 76, 60)));
        jPanel7.setForeground(new java.awt.Color(231, 76, 60));

        jPanel8.setBackground(new java.awt.Color(92, 151, 191));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Circled User Male_32px_1.png"))); // NOI18N
        jLabel5.setText("Lihat Semua Status Order");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtFilterTBUser.setBackground(new java.awt.Color(41, 128, 185));
        txtFilterTBUser.setForeground(new java.awt.Color(255, 255, 255));
        txtFilterTBUser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btnSedangDiProses.setBackground(new java.awt.Color(25, 181, 254));
        btnSedangDiProses.setForeground(new java.awt.Color(255, 255, 255));
        btnSedangDiProses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Spinner Frame 5_32px.png"))); // NOI18N
        btnSedangDiProses.setText("Di Proses");
        btnSedangDiProses.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSedangDiProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSedangDiProsesActionPerformed(evt);
            }
        });

        btnSudahDiAmbil.setBackground(new java.awt.Color(25, 181, 254));
        btnSudahDiAmbil.setForeground(new java.awt.Color(255, 255, 255));
        btnSudahDiAmbil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Buy_32px.png"))); // NOI18N
        btnSudahDiAmbil.setText("Sudah Di Ambil");
        btnSudahDiAmbil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSudahDiAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSudahDiAmbilActionPerformed(evt);
            }
        });

        btnBelumDiAmbil.setBackground(new java.awt.Color(25, 181, 254));
        btnBelumDiAmbil.setForeground(new java.awt.Color(255, 255, 255));
        btnBelumDiAmbil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Clear Shopping Cart_32px.png"))); // NOI18N
        btnBelumDiAmbil.setText("Belum Di Ambil");
        btnBelumDiAmbil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBelumDiAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBelumDiAmbilActionPerformed(evt);
            }
        });

        btnHapusOrder.setBackground(new java.awt.Color(25, 181, 254));
        btnHapusOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Trash_32px.png"))); // NOI18N
        btnHapusOrder.setText("Hapus Order");
        btnHapusOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapusOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusOrderActionPerformed(evt);
            }
        });

        TableBelumDiCuci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "No Nota", "Tanggal", "ID Pelanggan", "Nama Pelanggan", "Estimasi", "Pengambilan", "Total", "Status Pemesana", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableBelumDiCuci);

        javax.swing.GroupLayout PanelBelumDiCuciLayout = new javax.swing.GroupLayout(PanelBelumDiCuci);
        PanelBelumDiCuci.setLayout(PanelBelumDiCuciLayout);
        PanelBelumDiCuciLayout.setHorizontalGroup(
            PanelBelumDiCuciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBelumDiCuciLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(btnHapusOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSudahDiAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBelumDiAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSedangDiProses, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilterTBUser, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        PanelBelumDiCuciLayout.setVerticalGroup(
            PanelBelumDiCuciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBelumDiCuciLayout.createSequentialGroup()
                .addGroup(PanelBelumDiCuciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBelumDiCuciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSedangDiProses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSudahDiAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBelumDiAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapusOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFilterTBUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
        );

        TabPanel.addTab("BELUM DICUCI", PanelBelumDiCuci);

        txtFilterTBUser1.setBackground(new java.awt.Color(41, 128, 185));
        txtFilterTBUser1.setForeground(new java.awt.Color(255, 255, 255));
        txtFilterTBUser1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btnSudahDiAmbil1.setBackground(new java.awt.Color(25, 181, 254));
        btnSudahDiAmbil1.setForeground(new java.awt.Color(255, 255, 255));
        btnSudahDiAmbil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Buy_32px.png"))); // NOI18N
        btnSudahDiAmbil1.setText("Sudah Di Ambil");
        btnSudahDiAmbil1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSudahDiAmbil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSudahDiAmbil1ActionPerformed(evt);
            }
        });

        btnBelumDiAmbil1.setBackground(new java.awt.Color(25, 181, 254));
        btnBelumDiAmbil1.setForeground(new java.awt.Color(255, 255, 255));
        btnBelumDiAmbil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Clear Shopping Cart_32px.png"))); // NOI18N
        btnBelumDiAmbil1.setText("Belum Di Ambil");
        btnBelumDiAmbil1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBelumDiAmbil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBelumDiAmbil1ActionPerformed(evt);
            }
        });

        btnHapusOrder1.setBackground(new java.awt.Color(25, 181, 254));
        btnHapusOrder1.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusOrder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Trash_32px.png"))); // NOI18N
        btnHapusOrder1.setText("Hapus Order");
        btnHapusOrder1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapusOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusOrder1ActionPerformed(evt);
            }
        });

        TableSedangDiProses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "No Nota", "Tanggal Order", "Tanggal Update", "ID Pelanggan", "Nama Pelanggan", "Estimasi", "Pengambilan", "Total", "Status Pemesana", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TableSedangDiProses);

        javax.swing.GroupLayout PanelSedangDiProsesLayout = new javax.swing.GroupLayout(PanelSedangDiProses);
        PanelSedangDiProses.setLayout(PanelSedangDiProsesLayout);
        PanelSedangDiProsesLayout.setHorizontalGroup(
            PanelSedangDiProsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSedangDiProsesLayout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(btnHapusOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSudahDiAmbil1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBelumDiAmbil1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilterTBUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane3)
        );
        PanelSedangDiProsesLayout.setVerticalGroup(
            PanelSedangDiProsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSedangDiProsesLayout.createSequentialGroup()
                .addGroup(PanelSedangDiProsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSedangDiProsesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSudahDiAmbil1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBelumDiAmbil1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapusOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFilterTBUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabPanel.addTab("SEDANG DI PROSES", PanelSedangDiProses);

        txtFilterTBUser2.setBackground(new java.awt.Color(41, 128, 185));
        txtFilterTBUser2.setForeground(new java.awt.Color(255, 255, 255));
        txtFilterTBUser2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btnSudahDiAmbil2.setBackground(new java.awt.Color(25, 181, 254));
        btnSudahDiAmbil2.setForeground(new java.awt.Color(255, 255, 255));
        btnSudahDiAmbil2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Buy_32px.png"))); // NOI18N
        btnSudahDiAmbil2.setText("Sudah Di Ambil");
        btnSudahDiAmbil2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSudahDiAmbil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSudahDiAmbil2ActionPerformed(evt);
            }
        });

        btnHapusOrder2.setBackground(new java.awt.Color(25, 181, 254));
        btnHapusOrder2.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusOrder2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Trash_32px.png"))); // NOI18N
        btnHapusOrder2.setText("Hapus Order");
        btnHapusOrder2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapusOrder2.setPreferredSize(new java.awt.Dimension(107, 33));
        btnHapusOrder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusOrder2ActionPerformed(evt);
            }
        });

        TableBelumDiAmbil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "No Nota", "Tanggal Order", "Tanggal Update", "ID Pelanggan", "Nama Pelanggan", "Estimasi", "Pengambilan", "Total", "Status Pemesana", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(TableBelumDiAmbil);

        javax.swing.GroupLayout PanelBelumDiCuci2Layout = new javax.swing.GroupLayout(PanelBelumDiCuci2);
        PanelBelumDiCuci2.setLayout(PanelBelumDiCuci2Layout);
        PanelBelumDiCuci2Layout.setHorizontalGroup(
            PanelBelumDiCuci2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBelumDiCuci2Layout.createSequentialGroup()
                .addContainerGap(440, Short.MAX_VALUE)
                .addComponent(btnHapusOrder2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSudahDiAmbil2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilterTBUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane6)
        );
        PanelBelumDiCuci2Layout.setVerticalGroup(
            PanelBelumDiCuci2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBelumDiCuci2Layout.createSequentialGroup()
                .addGroup(PanelBelumDiCuci2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSudahDiAmbil2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFilterTBUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnHapusOrder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
        );

        TabPanel.addTab("BELUM DI AMBIL", PanelBelumDiCuci2);

        txtFilterTBUser3.setBackground(new java.awt.Color(41, 128, 185));
        txtFilterTBUser3.setForeground(new java.awt.Color(255, 255, 255));
        txtFilterTBUser3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btnHapusOrder3.setBackground(new java.awt.Color(25, 181, 254));
        btnHapusOrder3.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusOrder3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Trash_32px.png"))); // NOI18N
        btnHapusOrder3.setText("Hapus Order");
        btnHapusOrder3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapusOrder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusOrder3ActionPerformed(evt);
            }
        });

        TableSudahDiAmbil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "No Nota", "Tanggal Order", "Tanggal Update", "ID Pelanggan", "Nama Pelanggan", "Estimasi", "Pengambilan", "Total", "Status Pemesana", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(TableSudahDiAmbil);

        javax.swing.GroupLayout PanelBelumDiCuci3Layout = new javax.swing.GroupLayout(PanelBelumDiCuci3);
        PanelBelumDiCuci3.setLayout(PanelBelumDiCuci3Layout);
        PanelBelumDiCuci3Layout.setHorizontalGroup(
            PanelBelumDiCuci3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBelumDiCuci3Layout.createSequentialGroup()
                .addContainerGap(558, Short.MAX_VALUE)
                .addComponent(btnHapusOrder3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilterTBUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane7)
        );
        PanelBelumDiCuci3Layout.setVerticalGroup(
            PanelBelumDiCuci3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBelumDiCuci3Layout.createSequentialGroup()
                .addGroup(PanelBelumDiCuci3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFilterTBUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusOrder3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
        );

        TabPanel.addTab("SUDAH DI AMBIL", PanelBelumDiCuci3);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPanel)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TabPanel)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUtamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuUtamaActionPerformed

    private void btnBelumDiAmbil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBelumDiAmbil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBelumDiAmbil1ActionPerformed

    private void btnSudahDiAmbil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSudahDiAmbil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSudahDiAmbil1ActionPerformed

    private void btnBelumDiAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBelumDiAmbilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBelumDiAmbilActionPerformed

    private void btnSudahDiAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSudahDiAmbilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSudahDiAmbilActionPerformed

    private void btnSedangDiProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSedangDiProsesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSedangDiProsesActionPerformed

    private void btnSudahDiAmbil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSudahDiAmbil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSudahDiAmbil2ActionPerformed

    public JButton getBtnBelumDiAmbil() {
        return btnBelumDiAmbil;
    }

    public JButton getBtnBelumDiAmbil1() {
        return btnBelumDiAmbil1;
    }

    public JButton getBtnHapusOrder() {
        return btnHapusOrder;
    }

    public JButton getBtnHapusOrder1() {
        return btnHapusOrder1;
    }

    public JButton getBtnHapusOrder2() {
        return btnHapusOrder2;
    }

    public JButton getBtnHapusOrder3() {
        return btnHapusOrder3;
    }

    public JButton getBtnSedangDiProses() {
        return btnSedangDiProses;
    }

    public JButton getBtnSudahDiAmbil() {
        return btnSudahDiAmbil;
    }

    public JButton getBtnSudahDiAmbil1() {
        return btnSudahDiAmbil1;
    }

    public JButton getBtnSudahDiAmbil2() {
        return btnSudahDiAmbil2;
    }

    public JTextField getTxtFilterTBUser() {
        return txtFilterTBUser;
    }

    public JTextField getTxtFilterTBUser1() {
        return txtFilterTBUser1;
    }

    public JTextField getTxtFilterTBUser2() {
        return txtFilterTBUser2;
    }

    public JTextField getTxtFilterTBUser3() {
        return txtFilterTBUser3;
    }

    private void btnHapusOrder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusOrder3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusOrder3ActionPerformed

    private void btnHapusOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusOrderActionPerformed

    private void btnHapusOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusOrder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusOrder1ActionPerformed

    private void btnHapusOrder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusOrder2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusOrder2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementOrder().setVisible(true);
                
            }
            
        });
       
    }

    public JTabbedPane getTabPanel() {
        return TabPanel;
    }

    public JTable getTableBelumDiAmbil() {
        return TableBelumDiAmbil;
    }

    public JTable getTableBelumDiCuci() {
        return TableBelumDiCuci;
    }

    public JTable getTableSedangDiProses() {
        return TableSedangDiProses;
    }

    public JTable getTableSudahDiAmbil() {
        return TableSudahDiAmbil;
    }

    public JButton getBtnLaporan() {
        return btnLaporan;
    }

    public JButton getBtnManajemenOrder() {
        return btnManajemenOrder;
    }

    public JButton getBtnManajemenPelanggan() {
        return btnManajemenPelanggan;
    }

    public JButton getBtnMenuUtama() {
        return btnMenuUtama;
    }

    public JButton getBtnMonitoring() {
        return btnMonitoring;
    }

    public JButton getBtnPengaturan() {
        return btnPengaturan;
    }

    public JLabel getTxtAlamatLaundry() {
        return txtAlamatLaundry;
    }

    public JLabel getTxtJudulLaundry() {
        return txtJudulLaundry;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBelumDiCuci;
    private javax.swing.JPanel PanelBelumDiCuci2;
    private javax.swing.JPanel PanelBelumDiCuci3;
    private javax.swing.JPanel PanelSedangDiProses;
    private javax.swing.JTabbedPane TabPanel;
    private javax.swing.JTable TableBelumDiAmbil;
    private javax.swing.JTable TableBelumDiCuci;
    private javax.swing.JTable TableSedangDiProses;
    private javax.swing.JTable TableSudahDiAmbil;
    private javax.swing.JButton btnBelumDiAmbil;
    private javax.swing.JButton btnBelumDiAmbil1;
    private javax.swing.JButton btnHapusOrder;
    private javax.swing.JButton btnHapusOrder1;
    private javax.swing.JButton btnHapusOrder2;
    private javax.swing.JButton btnHapusOrder3;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnManajemenOrder;
    private javax.swing.JButton btnManajemenPelanggan;
    private javax.swing.JButton btnMenuUtama;
    private javax.swing.JButton btnMonitoring;
    private javax.swing.JButton btnPengaturan;
    private javax.swing.JButton btnSedangDiProses;
    private javax.swing.JButton btnSudahDiAmbil;
    private javax.swing.JButton btnSudahDiAmbil1;
    private javax.swing.JButton btnSudahDiAmbil2;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel txtAlamatLaundry;
    private javax.swing.JTextField txtFilterTBUser;
    private javax.swing.JTextField txtFilterTBUser1;
    private javax.swing.JTextField txtFilterTBUser2;
    private javax.swing.JTextField txtFilterTBUser3;
    private javax.swing.JLabel txtJudulLaundry;
    // End of variables declaration//GEN-END:variables
}
