/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author April10
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtJudulLaundry = new javax.swing.JLabel();
        btnMenuUtama = new javax.swing.JButton();
        btnManajemenPelanggan = new javax.swing.JButton();
        btnManajemenOrder = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnMonitoring = new javax.swing.JButton();
        btnPengaturan = new javax.swing.JButton();
        txtAlamatLaundry = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnTambahPelanggan = new javax.swing.JButton();
        txtKode = new javax.swing.JTextField();
        txtDaftarNama = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        btnTambahKeDataPemesanan = new javax.swing.JButton();
        btnClearCariPelanggan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        comboJenisLaundry = new javax.swing.JComboBox<>();
        comboPaketLoundry = new javax.swing.JComboBox<>();
        comboSatuanUkur = new javax.swing.JComboBox<>();
        comboJenisParfum = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableTransaksiLoundry = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnHapusDaftar = new javax.swing.JButton();
        comboItem = new javax.swing.JComboBox<>();
        Harga = new javax.swing.JTextField();
        txtTotalBayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUangYangDiBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        txtUkuran = new javax.swing.JSpinner();
        btnUbahDaftar = new javax.swing.JButton();
        btnTambahKeDaftar = new javax.swing.JButton();
        btnClearInput = new javax.swing.JButton();
        btnClearDataCucian = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtNamaPemesan = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        radionAmbilSendiri = new javax.swing.JRadioButton();
        radioExspress = new javax.swing.JRadioButton();
        radioDiantar = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtBiayaTambahan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();
        txtEstimasi = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKeteranga = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        txtIDPemesan = new javax.swing.JTextField();
        btnClearDataPemesan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(108, 122, 137));

        txtJudulLaundry.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        txtJudulLaundry.setForeground(new java.awt.Color(255, 255, 255));
        txtJudulLaundry.setText("Nama Laundry");

        btnMenuUtama.setBackground(new java.awt.Color(92, 151, 191));
        btnMenuUtama.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMenuUtama.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Home_32px.png"))); // NOI18N
        btnMenuUtama.setText("    Menu Utama");
        btnMenuUtama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenuUtama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnManajemenPelanggan.setBackground(new java.awt.Color(92, 151, 191));
        btnManajemenPelanggan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnManajemenPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnManajemenPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/User Groups_32px_6.png"))); // NOI18N
        btnManajemenPelanggan.setText("    Pelanggan");
        btnManajemenPelanggan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManajemenPelanggan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnManajemenPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManajemenPelangganActionPerformed(evt);
            }
        });

        btnManajemenOrder.setBackground(new java.awt.Color(92, 151, 191));
        btnManajemenOrder.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnManajemenOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnManajemenOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Shopping Basket_32px.png"))); // NOI18N
        btnManajemenOrder.setText("    Pesanan");
        btnManajemenOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManajemenOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnLaporan.setBackground(new java.awt.Color(92, 151, 191));
        btnLaporan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Stocks_32px_3.png"))); // NOI18N
        btnLaporan.setText("    Laporan");
        btnLaporan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnMonitoring.setBackground(new java.awt.Color(92, 151, 191));
        btnMonitoring.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMonitoring.setForeground(new java.awt.Color(255, 255, 255));
        btnMonitoring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/System Information_32px.png"))); // NOI18N
        btnMonitoring.setText("    Monitoring");
        btnMonitoring.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMonitoring.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnPengaturan.setBackground(new java.awt.Color(92, 151, 191));
        btnPengaturan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnPengaturan.setForeground(new java.awt.Color(255, 255, 255));
        btnPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Settings_32px.png"))); // NOI18N
        btnPengaturan.setText("    Pengaturan");
        btnPengaturan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPengaturan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txtAlamatLaundry.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatLaundry.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAlamatLaundry.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamatLaundry.setText("Alamat");
        txtAlamatLaundry.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManajemenOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManajemenPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtJudulLaundry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAlamatLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMonitoring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtJudulLaundry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlamatLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManajemenPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManajemenOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMonitoring, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(108, 122, 137));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 76, 60)));
        jPanel3.setForeground(new java.awt.Color(231, 76, 60));

        jPanel4.setBackground(new java.awt.Color(92, 151, 191));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Circled User Male_32px_1.png"))); // NOI18N
        jLabel3.setText("Cari Pelanggan");

        btnTambahPelanggan.setBackground(new java.awt.Color(25, 181, 254));
        btnTambahPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Add User Male_32px.png"))); // NOI18N
        btnTambahPelanggan.setText("Tambah Pelanggan");
        btnTambahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTambahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        txtKode.setToolTipText("Masukan Kode Pelanggan");
        txtKode.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kode Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });

        txtDaftarNama.setToolTipText("Masukan Nama");
        txtDaftarNama.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nama", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txtDaftarNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDaftarNamaActionPerformed(evt);
            }
        });

        txtContact.setToolTipText("Masukan No Telp/Hp");
        txtContact.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kontak", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        btnTambahKeDataPemesanan.setBackground(new java.awt.Color(25, 181, 254));
        btnTambahKeDataPemesanan.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahKeDataPemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Add_32px.png"))); // NOI18N
        btnTambahKeDataPemesanan.setText("Tambah Ke Data Pemesanan");
        btnTambahKeDataPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKeDataPemesananActionPerformed(evt);
            }
        });

        btnClearCariPelanggan.setBackground(new java.awt.Color(25, 181, 254));
        btnClearCariPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnClearCariPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Eraser_32px.png"))); // NOI18N
        btnClearCariPelanggan.setText("Clear");
        btnClearCariPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCariPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDaftarNama, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnTambahKeDataPemesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClearCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtContact)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDaftarNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambahKeDataPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnClearCariPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 76, 60)));
        jPanel5.setForeground(new java.awt.Color(231, 76, 60));

        jPanel6.setBackground(new java.awt.Color(92, 151, 191));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Form_32px.png"))); // NOI18N
        jLabel4.setText("Form Order");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 76, 60)));
        jPanel7.setForeground(new java.awt.Color(231, 76, 60));

        jPanel8.setBackground(new java.awt.Color(92, 151, 191));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Circled User Male_32px_1.png"))); // NOI18N
        jLabel5.setText("Data Cucian");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setText("Transaksi Loundry");

        comboJenisLaundry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Jenis-", "Biasa/Umum", "Skala Besar", "Khusus" }));
        comboJenisLaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJenisLaundryActionPerformed(evt);
            }
        });

        comboPaketLoundry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Tipe-" }));
        comboPaketLoundry.setPreferredSize(new java.awt.Dimension(83, 20));
        comboPaketLoundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaketLoundryActionPerformed(evt);
            }
        });

        comboSatuanUkur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Satuan-" }));
        comboSatuanUkur.setPreferredSize(new java.awt.Dimension(83, 20));
        comboSatuanUkur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSatuanUkurActionPerformed(evt);
            }
        });

        comboJenisParfum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Parfum-" }));
        comboJenisParfum.setPreferredSize(new java.awt.Dimension(83, 20));
        comboJenisParfum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboJenisParfumActionPerformed(evt);
            }
        });

        TableTransaksiLoundry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Item", "Jenis Loundry", "Tipe Loundry", "Jenis Parfum", "Satuan Ukur", "Jml", "Harga"
            }
        ));
        jScrollPane2.setViewportView(TableTransaksiLoundry);
        if (TableTransaksiLoundry.getColumnModel().getColumnCount() > 0) {
            TableTransaksiLoundry.getColumnModel().getColumn(0).setMinWidth(30);
            TableTransaksiLoundry.getColumnModel().getColumn(0).setMaxWidth(30);
            TableTransaksiLoundry.getColumnModel().getColumn(1).setPreferredWidth(40);
            TableTransaksiLoundry.getColumnModel().getColumn(2).setPreferredWidth(40);
            TableTransaksiLoundry.getColumnModel().getColumn(3).setPreferredWidth(40);
            TableTransaksiLoundry.getColumnModel().getColumn(4).setPreferredWidth(40);
            TableTransaksiLoundry.getColumnModel().getColumn(5).setPreferredWidth(40);
            TableTransaksiLoundry.getColumnModel().getColumn(6).setMinWidth(30);
            TableTransaksiLoundry.getColumnModel().getColumn(6).setPreferredWidth(30);
            TableTransaksiLoundry.getColumnModel().getColumn(6).setMaxWidth(30);
            TableTransaksiLoundry.getColumnModel().getColumn(7).setPreferredWidth(40);
        }

        jLabel7.setText("Daftar Transaksi");

        btnHapusDaftar.setBackground(new java.awt.Color(25, 181, 254));
        btnHapusDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Trash_32px.png"))); // NOI18N
        btnHapusDaftar.setText("Hapus");
        btnHapusDaftar.setPreferredSize(new java.awt.Dimension(107, 41));
        btnHapusDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDaftarActionPerformed(evt);
            }
        });

        comboItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Item-" }));
        comboItem.setMinimumSize(new java.awt.Dimension(83, 20));
        comboItem.setPreferredSize(new java.awt.Dimension(83, 20));
        comboItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboItemActionPerformed(evt);
            }
        });

        Harga.setPreferredSize(new java.awt.Dimension(83, 20));
        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });

        txtTotalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBayarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Total Bayar");

        txtUangYangDiBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangYangDiBayarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Uang Yang Di Bayar");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Kembalian");

        txtKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKembalianActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");

        btnHitung.setText("Hitung");

        txtUkuran.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        btnUbahDaftar.setBackground(new java.awt.Color(25, 181, 254));
        btnUbahDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnUbahDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Replace_32px.png"))); // NOI18N
        btnUbahDaftar.setText("Ubah");
        btnUbahDaftar.setPreferredSize(new java.awt.Dimension(107, 41));
        btnUbahDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahDaftarActionPerformed(evt);
            }
        });

        btnTambahKeDaftar.setBackground(new java.awt.Color(25, 181, 254));
        btnTambahKeDaftar.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahKeDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Add_32px.png"))); // NOI18N
        btnTambahKeDaftar.setText("Tambah");
        btnTambahKeDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKeDaftarActionPerformed(evt);
            }
        });

        btnClearInput.setBackground(new java.awt.Color(25, 181, 254));
        btnClearInput.setForeground(new java.awt.Color(255, 255, 255));
        btnClearInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Eraser_32px.png"))); // NOI18N
        btnClearInput.setText("Clear");
        btnClearInput.setPreferredSize(new java.awt.Dimension(107, 41));
        btnClearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearInputActionPerformed(evt);
            }
        });

        btnClearDataCucian.setText("Clear All Data");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboJenisLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(comboPaketLoundry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(comboJenisParfum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboSatuanUkur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(btnClearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnHapusDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnUbahDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnTambahKeDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 9, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnClearDataCucian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUangYangDiBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboJenisLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPaketLoundry, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboItem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboJenisParfum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSatuanUkur, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUbahDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambahKeDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHapusDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUangYangDiBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearDataCucian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 76, 60)));
        jPanel15.setForeground(new java.awt.Color(231, 76, 60));

        jPanel16.setBackground(new java.awt.Color(92, 151, 191));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Circled User Male_32px_1.png"))); // NOI18N
        jLabel6.setText("Data Pemesan");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtNamaPemesan.setBackground(new java.awt.Color(240, 240, 240));
        txtNamaPemesan.setBorder(javax.swing.BorderFactory.createTitledBorder("Nama Pelanggan"));
        txtNamaPemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPemesanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        radionAmbilSendiri.setText("Diambil Sendiri");
        radionAmbilSendiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radionAmbilSendiriActionPerformed(evt);
            }
        });

        radioExspress.setText("Kilat");
        radioExspress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioExspressActionPerformed(evt);
            }
        });

        radioDiantar.setText("Diantar");
        radioDiantar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDiantarActionPerformed(evt);
            }
        });

        jLabel10.setText("Pengambilan *");

        jLabel12.setText("Hari");

        jLabel11.setText("Estimasi");

        jLabel13.setText("Biaya Tambahan");

        jLabel14.setText("Diskon");

        txtEstimasi.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioExspress)
                            .addComponent(radioDiantar)
                            .addComponent(radionAmbilSendiri))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))))
                .addGap(10, 10, 10)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addComponent(txtEstimasi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(txtBiayaTambahan)
                    .addComponent(txtDiskon))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radionAmbilSendiri)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtEstimasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDiantar)
                    .addComponent(jLabel13)
                    .addComponent(txtBiayaTambahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioExspress)
                    .addComponent(jLabel14)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        txtKeteranga.setColumns(20);
        txtKeteranga.setRows(5);
        jScrollPane1.setViewportView(txtKeteranga);

        jLabel15.setText("Keterangan");

        txtIDPemesan.setBackground(new java.awt.Color(240, 240, 240));
        txtIDPemesan.setBorder(javax.swing.BorderFactory.createTitledBorder("Kode Pelanggan"));

        btnClearDataPemesan.setText("Clear Data Pemesan");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(btnClearDataPemesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(txtIDPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNamaPemesan))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15)))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearDataPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahPelangganActionPerformed

    private void radioExspressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioExspressActionPerformed
        // TODO add your handling code here:
        radionAmbilSendiri.setSelected(false);
        radioDiantar.setSelected(false);
        txtBiayaTambahan.setEditable(true);
    }//GEN-LAST:event_radioExspressActionPerformed

    private void radioDiantarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDiantarActionPerformed
        // TODO add your handling code here:
        radioExspress.setSelected(false);
        radionAmbilSendiri.setSelected(false);
        txtBiayaTambahan.setEditable(true);
    }//GEN-LAST:event_radioDiantarActionPerformed

    private void radionAmbilSendiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radionAmbilSendiriActionPerformed
        // TODO add your handling code here:
        radioExspress.setSelected(false);
        radioDiantar.setSelected(false);
        txtBiayaTambahan.setEditable(false);
    }//GEN-LAST:event_radionAmbilSendiriActionPerformed

    private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeActionPerformed

    private void txtDaftarNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDaftarNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDaftarNamaActionPerformed

    public JButton getBtnClearCariPelanggan() {
        return btnClearCariPelanggan;
    }

    public JButton getBtnClearDataCucian() {
        return btnClearDataCucian;
    }

    public JButton getBtnClearDataPemesan() {
        return btnClearDataPemesan;
    }

    public JButton getBtnClearInput() {
        return btnClearInput;
    }

    public JButton getBtnHapusDaftar() {
        return btnHapusDaftar;
    }

    public JButton getBtnTambahKeDataPemesanan() {
        return btnTambahKeDataPemesanan;
    }

    public JButton getBtnUbahDaftar() {
        return btnUbahDaftar;
    }

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void comboJenisLaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJenisLaundryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJenisLaundryActionPerformed

    private void comboPaketLoundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaketLoundryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPaketLoundryActionPerformed

    private void comboSatuanUkurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSatuanUkurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSatuanUkurActionPerformed

    private void comboJenisParfumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboJenisParfumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboJenisParfumActionPerformed

    private void btnHapusDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusDaftarActionPerformed

    private void txtNamaPemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPemesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPemesanActionPerformed

    private void comboItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboItemActionPerformed

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaActionPerformed

    private void txtTotalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBayarActionPerformed

    private void txtUangYangDiBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangYangDiBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUangYangDiBayarActionPerformed

    private void txtKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianActionPerformed

    private void btnManajemenPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManajemenPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManajemenPelangganActionPerformed

    private void btnUbahDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahDaftarActionPerformed

    private void btnTambahKeDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKeDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahKeDaftarActionPerformed

    private void btnTambahKeDataPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKeDataPemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahKeDataPemesananActionPerformed

    private void btnClearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearInputActionPerformed

    private void btnClearCariPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCariPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearCariPelangganActionPerformed

    public void setTxtKembalian(JTextField txtKembalian) {
        this.txtKembalian = txtKembalian;
    }

    public JButton getBtnHitung() {
        return btnHitung;
    }

    public JTextField getTxtKembalian() {
        return txtKembalian;
    }

    public JTextField getTxtTotalBayar() {
        return txtTotalBayar;
    }

    public JTextField getTxtUangYangDiBayar() {
        return txtUangYangDiBayar;
    }

    public JTable getTableTransaksiLoundry() {
        return TableTransaksiLoundry;
    }

    public JTextField getHarga() {
        return Harga;
    }

    public JComboBox<String> getComboItem() {
        return comboItem;
    }

    public JButton getBtnTambahKeDaftar() {
        return btnTambahKeDaftar;
    }

    public JComboBox<String> getComboJenisLaundry() {
        return comboJenisLaundry;
    }

    public JComboBox<String> getComboJenisParfum() {
        return comboJenisParfum;
    }

    public JComboBox<String> getComboPaketLoundry() {
        return comboPaketLoundry;
    }

    public JComboBox<String> getComboSatuanUkur() {
        return comboSatuanUkur;
    }

    public JTextField getTxtIDPemesan() {
        return txtIDPemesan;
    }

    public JTextField getTxtNamaPemesan() {
        return txtNamaPemesan;
    }

    public JLabel getTxtAlamatLaundry() {
        return txtAlamatLaundry;
    }

    public JLabel getTxtJudulLaundry() {
        return txtJudulLaundry;
    }

    public JSpinner getTxtUkuran() {
        return txtUkuran;
    }

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    public JButton getBtnLaporan() {
        return btnLaporan;
    }

    public void setBtnLaporan(JButton btnLaporan) {
        this.btnLaporan = btnLaporan;
    }

    public JButton getBtnManajemenOrder() {
        return btnManajemenOrder;
    }

    public void setBtnManajemenOrder(JButton btnManajemenOrder) {
        this.btnManajemenOrder = btnManajemenOrder;
    }

    public JButton getBtnManajemenPelanggan() {
        return btnManajemenPelanggan;
    }

    public void setBtnManajemenPelanggan(JButton btnManajemenPelanggan) {
        this.btnManajemenPelanggan = btnManajemenPelanggan;
    }

    public JButton getBtnMenuUtama() {
        return btnMenuUtama;
    }

    public void setBtnMenuUtama(JButton btnMenuUtama) {
        this.btnMenuUtama = btnMenuUtama;
    }

    public JButton getBtnMonitoring() {
        return btnMonitoring;
    }

    public void setBtnMonitoring(JButton btnMonitoring) {
        this.btnMonitoring = btnMonitoring;
    }

    public JButton getBtnPengaturan() {
        return btnPengaturan;
    }

    public void setBtnPengaturan(JButton btnPengaturan) {
        this.btnPengaturan = btnPengaturan;
    }

    public JButton getBtnSimpan() {
        return btnSimpan;
    }

    public void setBtnSimpan(JButton btnSimpan) {
        this.btnSimpan = btnSimpan;
    }

    public JButton getBtnTambahPelanggan() {
        return btnTambahPelanggan;
    }

    public void setBtnTambahPelanggan(JButton btnTambahPelanggan) {
        this.btnTambahPelanggan = btnTambahPelanggan;
    }

    public ButtonGroup getButtonGroup2() {
        return buttonGroup2;
    }

    public void setButtonGroup2(ButtonGroup buttonGroup2) {
        this.buttonGroup2 = buttonGroup2;
    }

    public ButtonGroup getButtonGroup3() {
        return buttonGroup3;
    }

    public void setButtonGroup3(ButtonGroup buttonGroup3) {
        this.buttonGroup3 = buttonGroup3;
    }



    public JRadioButton getRadioDiantar() {
        return radioDiantar;
    }

    public void setRadioDiantar(JRadioButton radioDiantar) {
        this.radioDiantar = radioDiantar;
    }

    public JRadioButton getRadioExspress() {
        return radioExspress;
    }

    public void setRadioExspress(JRadioButton radioExspress) {
        this.radioExspress = radioExspress;
    }

    public JRadioButton getRadionAmbilSendiri() {
        return radionAmbilSendiri;
    }

    public void setRadionAmbilSendiri(JRadioButton radionAmbilSendiri) {
        this.radionAmbilSendiri = radionAmbilSendiri;
    }

    public JTextField getTxtBiayaTambahan() {
        return txtBiayaTambahan;
    }

    public void setTxtBiayaTambahan(JTextField txtBiayaTambahan) {
        this.txtBiayaTambahan = txtBiayaTambahan;
    }

    public JTextField getTxtContact() {
        return txtContact;
    }

    public void setTxtContact(JTextField txtContact) {
        this.txtContact = txtContact;
    }

    public JTextField getTxtDaftarNama() {
        return txtDaftarNama;
    }

    public void setTxtDaftarNama(JTextField txtDaftarNama) {
        this.txtDaftarNama = txtDaftarNama;
    }

    public JTextField getTxtDiskon() {
        return txtDiskon;
    }

    public void setTxtDiskon(JTextField txtDiskon) {
        this.txtDiskon = txtDiskon;
    }

    public JSpinner getTxtEstimasi() {
        return txtEstimasi;
    }
 

    public JTextField getTxtIDPelanggan() {
        return txtNamaPemesan;
    }

    public void setTxtIDPelanggan(JTextField txtIDPelanggan) {
        this.txtNamaPemesan = txtIDPelanggan;
    }

    public JTextArea getTxtKeteranga() {
        return txtKeteranga;
    }

    public void setTxtKeteranga(JTextArea txtKeteranga) {
        this.txtKeteranga = txtKeteranga;
    }

    public JTextField getTxtKode() {
        return txtKode;
    }

    public void setTxtKode(JTextField txtKode) {
        this.txtKode = txtKode;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Harga;
    private javax.swing.JTable TableTransaksiLoundry;
    private javax.swing.JButton btnClearCariPelanggan;
    private javax.swing.JButton btnClearDataCucian;
    private javax.swing.JButton btnClearDataPemesan;
    private javax.swing.JButton btnClearInput;
    private javax.swing.JButton btnHapusDaftar;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnManajemenOrder;
    private javax.swing.JButton btnManajemenPelanggan;
    private javax.swing.JButton btnMenuUtama;
    private javax.swing.JButton btnMonitoring;
    private javax.swing.JButton btnPengaturan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahKeDaftar;
    private javax.swing.JButton btnTambahKeDataPemesanan;
    private javax.swing.JButton btnTambahPelanggan;
    private javax.swing.JButton btnUbahDaftar;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comboItem;
    private javax.swing.JComboBox<String> comboJenisLaundry;
    private javax.swing.JComboBox<String> comboJenisParfum;
    private javax.swing.JComboBox<String> comboPaketLoundry;
    private javax.swing.JComboBox<String> comboSatuanUkur;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radioDiantar;
    private javax.swing.JRadioButton radioExspress;
    private javax.swing.JRadioButton radionAmbilSendiri;
    private javax.swing.JLabel txtAlamatLaundry;
    private javax.swing.JTextField txtBiayaTambahan;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDaftarNama;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JSpinner txtEstimasi;
    private javax.swing.JTextField txtIDPemesan;
    private javax.swing.JLabel txtJudulLaundry;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextArea txtKeteranga;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNamaPemesan;
    private javax.swing.JTextField txtTotalBayar;
    private javax.swing.JTextField txtUangYangDiBayar;
    private javax.swing.JSpinner txtUkuran;
    // End of variables declaration//GEN-END:variables
}
