/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.toedter.calendar.JDateChooser;
import javafx.scene.control.TabPane;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author April10
 */
public class Monitoring extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public Monitoring() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        sidePanel = new javax.swing.JPanel();
        txtJudulLaundry = new javax.swing.JLabel();
        txtAlamatLaundry = new javax.swing.JLabel();
        btnMenuUtama = new javax.swing.JButton();
        btnManajemenPelanggan = new javax.swing.JButton();
        btnManajemenOrder = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnMonitoring = new javax.swing.JButton();
        btnPengaturan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnHapusLog = new javax.swing.JButton();
        txtFilterLog = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Monitoring = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        comboJenisLog = new javax.swing.JComboBox<>();
        Tgl_Dari = new com.toedter.calendar.JDateChooser();
        Tgl_Sampai = new com.toedter.calendar.JDateChooser();
        btnCari = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 240, 241));
        setPreferredSize(new java.awt.Dimension(1143, 633));

        sidePanel.setBackground(new java.awt.Color(108, 122, 137));
        sidePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtJudulLaundry.setBackground(new java.awt.Color(255, 255, 255));
        txtJudulLaundry.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        txtJudulLaundry.setForeground(new java.awt.Color(255, 255, 255));
        txtJudulLaundry.setText("Nama Laundry");

        txtAlamatLaundry.setBackground(new java.awt.Color(255, 255, 255));
        txtAlamatLaundry.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAlamatLaundry.setForeground(new java.awt.Color(255, 255, 255));
        txtAlamatLaundry.setText("Alamat");
        txtAlamatLaundry.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnMenuUtama.setBackground(new java.awt.Color(92, 151, 191));
        btnMenuUtama.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMenuUtama.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuUtama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Home_32px.png"))); // NOI18N
        btnMenuUtama.setText("    Menu Utama");
        btnMenuUtama.setToolTipText("");
        btnMenuUtama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMenuUtama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuUtamaActionPerformed(evt);
            }
        });

        btnManajemenPelanggan.setBackground(new java.awt.Color(92, 151, 191));
        btnManajemenPelanggan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnManajemenPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        btnManajemenPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/User Groups_32px_6.png"))); // NOI18N
        btnManajemenPelanggan.setText("    Pelanggan");
        btnManajemenPelanggan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManajemenPelanggan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnManajemenOrder.setBackground(new java.awt.Color(92, 151, 191));
        btnManajemenOrder.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnManajemenOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnManajemenOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Shopping Basket_32px.png"))); // NOI18N
        btnManajemenOrder.setText("    Pesanan");
        btnManajemenOrder.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManajemenOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnLaporan.setBackground(new java.awt.Color(92, 151, 191));
        btnLaporan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Stocks_32px_3.png"))); // NOI18N
        btnLaporan.setText("    Laporan");
        btnLaporan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnMonitoring.setBackground(new java.awt.Color(92, 151, 191));
        btnMonitoring.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnMonitoring.setForeground(new java.awt.Color(255, 255, 255));
        btnMonitoring.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/System Information_32px.png"))); // NOI18N
        btnMonitoring.setText("    Monitoring");
        btnMonitoring.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMonitoring.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnPengaturan.setBackground(new java.awt.Color(92, 151, 191));
        btnPengaturan.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnPengaturan.setForeground(new java.awt.Color(255, 255, 255));
        btnPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Settings_32px.png"))); // NOI18N
        btnPengaturan.setText("    Pengaturan");
        btnPengaturan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPengaturan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jSeparator1.setBackground(new java.awt.Color(189, 195, 199));
        jSeparator1.setForeground(new java.awt.Color(189, 195, 199));

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAlamatLaundry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMonitoring, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManajemenOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManajemenPelanggan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtJudulLaundry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtJudulLaundry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlamatLaundry, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManajemenPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManajemenOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMonitoring, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(108, 122, 137));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(92, 151, 191));

        jLabel4.setBackground(new java.awt.Color(44, 62, 80));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Form_32px.png"))); // NOI18N
        jLabel4.setText("Lihat Aktivitas User");

        btnHapusLog.setBackground(new java.awt.Color(41, 128, 185));
        btnHapusLog.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Delete File_26px.png"))); // NOI18N
        btnHapusLog.setText("Hapus Log Yang Di Pilih");
        btnHapusLog.setBorder(null);

        txtFilterLog.setBackground(new java.awt.Color(41, 128, 185));
        txtFilterLog.setForeground(new java.awt.Color(255, 255, 255));
        txtFilterLog.setToolTipText("Cari Log");
        txtFilterLog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari Log", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFilterLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFilterLog, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapusLog, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHapusLog, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(txtFilterLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        TB_Monitoring.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID_Log", "ID_User", "Nama Pegawai", "Level", "Tanggal Login", "Tanggal Logout"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TB_Monitoring);
        if (TB_Monitoring.getColumnModel().getColumnCount() > 0) {
            TB_Monitoring.getColumnModel().getColumn(0).setMinWidth(35);
            TB_Monitoring.getColumnModel().getColumn(0).setPreferredWidth(35);
            TB_Monitoring.getColumnModel().getColumn(0).setMaxWidth(35);
            TB_Monitoring.getColumnModel().getColumn(1).setMinWidth(70);
            TB_Monitoring.getColumnModel().getColumn(1).setPreferredWidth(70);
            TB_Monitoring.getColumnModel().getColumn(1).setMaxWidth(70);
            TB_Monitoring.getColumnModel().getColumn(2).setMinWidth(60);
            TB_Monitoring.getColumnModel().getColumn(2).setPreferredWidth(60);
            TB_Monitoring.getColumnModel().getColumn(2).setMaxWidth(60);
            TB_Monitoring.getColumnModel().getColumn(3).setMinWidth(150);
            TB_Monitoring.getColumnModel().getColumn(3).setPreferredWidth(150);
            TB_Monitoring.getColumnModel().getColumn(3).setMaxWidth(200);
            TB_Monitoring.getColumnModel().getColumn(4).setMinWidth(100);
            TB_Monitoring.getColumnModel().getColumn(4).setPreferredWidth(100);
            TB_Monitoring.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel11.setForeground(new java.awt.Color(231, 76, 60));

        jPanel12.setBackground(new java.awt.Color(92, 151, 191));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Form_32px.png"))); // NOI18N
        jLabel10.setText("Aksi");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        comboJenisLog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Jenis Log-", "Bulan Tertentu", "Hari Tertentu", "Sesuai Dengan Range" }));
        comboJenisLog.setBorder(null);

        Tgl_Dari.setBorder(javax.swing.BorderFactory.createTitledBorder("Dari Tanggal"));
        Tgl_Dari.setDateFormatString("dd-MMM-yyyy");

        Tgl_Sampai.setBorder(javax.swing.BorderFactory.createTitledBorder("Sampai Dengan"));
        Tgl_Sampai.setDateFormatString("dd-MMM-yyyy");

        btnCari.setBackground(new java.awt.Color(25, 181, 254));
        btnCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Search_26px.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.setBorder(null);

        btnClear.setBackground(new java.awt.Color(25, 181, 254));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icon/Eraser_26px.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(null);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboJenisLog, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tgl_Dari, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tgl_Sampai, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tgl_Dari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tgl_Sampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboJenisLog)
                    .addComponent(btnCari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 623, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuUtamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenuUtamaActionPerformed

    private void txtFilterLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterLogActionPerformed

    public JButton getBtnLaporan() {
        return btnLaporan;
    }

    public JButton getBtnManajemenOrder() {
        return btnManajemenOrder;
    }

    public JButton getBtnClear() {
        return btnClear;
    }

    public JButton getBtnManajemenPelanggan() {
        return btnManajemenPelanggan;
    }

    public JButton getBtnMenuUtama() {
        return btnMenuUtama;
    }

    public JButton getBtnMonitoring() {
        return btnMonitoring;
    }

    public JButton getBtnPengaturan() {
        return btnPengaturan;
    }

    public JLabel getTxtAlamatLaundry() {
        return txtAlamatLaundry;
    }

    public JLabel getTxtJudulLaundry() {
        return txtJudulLaundry;
    }

    public JTable getTB_Monitoring() {
        return TB_Monitoring;
    }

    public JDateChooser getTgl_Dari() {
        return Tgl_Dari;
    }

    public JDateChooser getTgl_Sampai() {
        return Tgl_Sampai;
    }

    public JComboBox<String> getComboJenisLog() {
        return comboJenisLog;
    }

    public JTextField getTxtFilterLog() {
        return txtFilterLog;
    }

    public JButton getBtnCari() {
        return btnCari;
    }

    public JButton getBtnHapusLog() {
        return btnHapusLog;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitoring.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monitoring().setVisible(true);
                
            }
            
        });
       
    }

    public JPanel getSidePanel() {
        return sidePanel;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB_Monitoring;
    private com.toedter.calendar.JDateChooser Tgl_Dari;
    private com.toedter.calendar.JDateChooser Tgl_Sampai;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapusLog;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnManajemenOrder;
    private javax.swing.JButton btnManajemenPelanggan;
    private javax.swing.JButton btnMenuUtama;
    private javax.swing.JButton btnMonitoring;
    private javax.swing.JButton btnPengaturan;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comboJenisLog;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel txtAlamatLaundry;
    private javax.swing.JTextField txtFilterLog;
    private javax.swing.JLabel txtJudulLaundry;
    // End of variables declaration//GEN-END:variables

}
